name: Daily Push Quote

on:
  schedule:
    - cron: '7 1 * * *'  # 台灣時間 09:07 (UTC+0 -> +8)
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Daily Push API
        run: |
      -H 'Authorization: Bearer {CHANNEL_ACCESS_TOKEN}'
      -H 'Content-Type:application/json'  
          curl -X GET line-bot-vercel-five.vercel.app/api/push
name: Daily Push Quote

on:
  schedule:
    - cron: '7 1 * * *'  # 台灣時間 09:07 (UTC+0 -> +8)
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Daily Push API
        run: |
      -H 'Authorization: Bearer {CHANNEL_ACCESS_TOKEN}'
      -H 'Content-Type:application/json'    
          curl -X GET line-bot-vercel-five.vercel.app/api/push
